app:
  name: "web_app"
  mode: "dev"
  port: 8081
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  # 备份数量
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "sql_demo"
redis:
  host: "127.0.0.1"
  port: 6379
  db: 0